### ISSUE TITLE
async invalid syntax

### ISSUE THREAD

**Issue by erooskie** [tweepy/tweepy#1017]
I'm fairly new to coding---just taking a coding class this semester. I'm using a MacBook Air and downloaded PyCharm, and so far, I've been able to figure most things out, but I'm stuck on this one.

I'm trying to get the tweepy Stream Listener to return the tweets for a certain hashtag, and this code worked without issue on the Windows computers on campus. 
The code I'm running looks like this:

    import tweepy
    #override tweepy.StreamListener to add logic to on_status
    class MyStreamListener(tweepy.StreamListener):

        def on_status(self, status):
            print(status.text)
    
        def on_error(self, status_code):
            if status_code == 420:
                # returning False in on_data disconnects the stream
                return False
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    
    myStreamListener = MyStreamListener()
    myStream = tweepy.Stream(auth, listener=myStreamListener)
    
    myStream.filter(track=['#fakenews'])

On my computer, it returns this error:

> Traceback (most recent call last):
>  File "/Users/USERNAME/PycharmProjects/Homework/Twitter.py", line 7, in <module>
    import tweepy
  File "/Users/USERNAME/PycharmProjects/Homework/venv/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/Users/USERNAME/PycharmProjects/Homework/venv/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                                     ^
SyntaxError: invalid syntax

The carat is actually under `async`, not at the beginning of the line. The last two "files" are the code from the tweepy module, not any code I've written or searched through.

I've tried changing the interpreter for my project in PyCharm, but I'm not sure what else to try. My professor looked at it and didn't want to get into the backend code (and honestly, I don't either, since I don't really know what I'm doing), so I'm stuck as to what to try next or actually what the real issue is. 

Any suggestions?

**Comment by stoictrader** [comment]
The same issue but on Windows10 x64 python3.7 beta, on python3.6 it works fine, so seems like incompatibility with python 3.7?

**Comment by hugovk** [comment]
https://github.com/tweepy/tweepy/pull/1042 has been merged. Can this be closed?

**Comment by skidzo** [comment]
this will stay an issue amongst users trying to pip install this package on python > 3.7(as there is no anaconda) when will you upload the fix?

**Comment by jordo1138** [comment]
the rename async to async_ had to be used with python 3.7 today

**Comment by gpoire** [comment]
If you want to replace async by async_ quickly :
sed -i 's/async/async_/g' /lib/python3.7/site-packages/tweepy/streaming.py

**Comment by kevcooper** [comment]
just a heads up for anyone trying to use @gpoire's solution on macOS - the command needs to be sed -i '' 's/async/async_/g' /lib/python3.7/site-packages/tweepy/streaming.py

**Comment by ssolidus** [comment]
Still encountering this issue - the above hacks are not solutions, the solution should be implemented in the module.

**Comment by hugovk** [comment]
It's been fixed in the module (https://github.com/tweepy/tweepy/pull/1042) we now need a release.

See https://github.com/tweepy/tweepy/issues/1063 that asks for a new release, and https://github.com/tweepy/tweepy/issues/792 for volunteers to help maintain this project.

Ping @joshthecoder @Aaron1011.

---

In the meantime, you can install from GitHub using:

```
pip install -U git+https://github.com/tweepy/tweepy.git
```

Or to pin to a given commit (this is the current latest):

```
pip install -U git+https://github.com/tweepy/tweepy.git@2efe385fc69385b57733f747ee62e6be12a1338b
```

**Comment by ashwinramr** [comment]
> It's been fixed in the module (#1042) we now need a release.
> 
> See #1063 that asks for a new release, and #792 for volunteers to help maintain this project.
> 
> Ping @joshthecoder @Aaron1011.
> 
> In the meantime, you can install from GitHub using:
> 
> ```
> pip install -U git+https://github.com/tweepy/tweepy.git
> ```
> 
> Or to pin to a given commit (this is the current latest):
> 
> ```
> pip install -U git+https://github.com/tweepy/tweepy.git@2efe385fc69385b57733f747ee62e6be12a1338b
> ```

I tried installing from github and still facing the issue. Looking forward to the new release.

**Comment by csavoia** [comment]
As a note to others, my `streaming.py` file contained the argument "async" rather than "#async" . The solution was the same, however: simply replacing all to "async_" .

Worked like a charm for me. Thank you!

**Comment by azizainunnajib** [comment]
i fond this. the default is not compatible with 3.7. but you this solution solve my problem, i install it in anaconda prompt (my pip working in python not in anaconda package).

> > It's been fixed in the module (#1042) we now need a release.
> > See #1063 that asks for a new release, and #792 for volunteers to help maintain this project.
> > Ping @joshthecoder @Aaron1011.
> > In the meantime, you can install from GitHub using:
> > ```
> > pip install -U git+https://github.com/tweepy/tweepy.git
> > ```
> > Or to pin to a given commit (this is the current latest):
> > ```
> > pip install -U git+https://github.com/tweepy/tweepy.git@2efe385fc69385b57733f747ee62e6be12a1338b
> > ```
> 
> I tried installing from github and still facing the issue. Looking forward to the new release.

**Comment by adjouden** [comment]
> As a note to others, my `streaming.py` file contained the argument "async" rather than "#async" . The solution was the same, however: simply replacing all to "async_" .
> 
> Worked like a charm for me. Thank you!

where do I find streaming.py ?

**Comment by Harmon758** [comment]
@adjouden Since this issue has already been fixed, just upgrade to the development version in this GitHub repository, instead of manually modifying the source files for the library.

**Comment by amidher** [comment]
for tweepy 3.7 try is_async=True instead of async=True. this did the job for me

**Comment by Tarandeepsingh436** [comment]
> The same issue but on Windows10 x64 python3.7 beta, on python3.6 it works fine, so seems like incompatibility with python 3.7? Okay found the solution. Apparently async cannot be used as an argument name in Python 3.7 So open streaming.py and replace #async with async_ it fixed the error for me.

can you tell me how we can replace ( streaming.py and replace #async with async_ it fixed the error for me.)

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.

This was fixed in Tweepy v3.7.0 over 3-4 years ago.
