### ISSUE TITLE
Tweepy does not handle 429 HTTP error (Too many Requests) - Service unavailable

### ISSUE THREAD

**Issue by toshiro92** [tweepy/tweepy#791]
Hello !

I am currently using Tweepy library (version 3.2.0 as the 3.6.0 does not working due to issue #576) , and I launched it since several days. However after a while, I received the following message between each tweet collected:

> HTTP Error 429: Too Many Requests

I then stopped it during 1 hour, and now I have between tweets the following messages:

> Service not available
> Service Timed out

I thought set as True the function `wait_on_rate_limit` while handle this kind of thing, or maybe it does not take account of 429 error ? I just requested about 10 terms in my filter, which returns around 1 tweet per 5-10 sec maximum, which seems to be a few.

How can I handle this kind of issue ? Is there a bug on it or something ? Or I reached the Twitter limit ? 

There is my piece of code btw:

```
streamer = tweepy.Stream(auth=api.auth, listener=StreamListener(), timeout=3000000000)
streamer.filter(None,terms)

class StreamListener(tweepy.StreamListener):
    status_wrapper = TextWrapper(width=60, initial_indent='    ', subsequent_indent='    ')

def on_status(self, status):
    print ('{} {} - {}'.format(status.author.screen_name, status.created_at,status.text))
    saveTweet(status)
def on_disconnect(self, notice):
    print ("Disconnect: {}".format(notice))
    return

def on_warning(self, notice):
    print ("Warning: {}".format(notice))
    return

def on_exception(self, exception):
    print ("Exception: ".format(exception))
    return
def on_error(self, status_code):
    if (status_code == 403):
         print("Limit probably reached")
    else:
         print("Error occured > {}".format(status_code))
    return False
```

**Comment by Aaron1011** [comment]
@toshiro92: I've fixed issue #576. The latest version of Tweepy should also handle 429 errors properly.

**Comment by toshiro92** [comment]
That's a good news @Aaron1011 , many thanks :)

**Comment by varun4github** [comment]
Hi Team , 

I am using tweepy (3.5.0) but still getting error "tweepy.error.TweepError: Twitter error response: status code = 429" . Any method we can avoid this ?

**Comment by fitnr** [comment]
@varun4github read Twitter's docs on [rate limiting](https://developer.twitter.com/en/docs/basics/rate-limiting)

**Comment by varun4github** [comment]
@fitnr Thank you for reply . I saw this while googling for this error . However, I also saw somewhere that there is fix for this using newer version of tweepy and that linked me onto this page . I doubted that something which is already limited by twitter then how it is possible to get rid of it . 
At the same time , I was also wondering that how come many applications are build on twitter and works fine with much more requests then what i am trying to make .
